/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TrieJNI */

#ifndef _Included_TrieJNI
#define _Included_TrieJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TrieJNI
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TrieJNI_initialize
  (JNIEnv *, jobject);

/*
 * Class:     TrieJNI
 * Method:    insert
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TrieJNI_insert
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     TrieJNI
 * Method:    lookup
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TrieJNI_lookup
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
