#include <jni.h>
#include "TrieJNI.h"  // This is the header file generated by javah
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define ALPHABET_SIZE 26

struct TrieNode {
    struct TrieNode* children[ALPHABET_SIZE];
    char* data;  // Stores the file path at the end node
    unsigned int isEndOfPath : 1;  // A single bit flag for end of path
};

// Global root node for the Trie
struct TrieNode* root = NULL;

// Forward declarations for insert and lookup functions
void insert(struct TrieNode* root, const char* path, const char* data);
char* lookup(struct TrieNode* root, const char* path);

// Create a new Trie node
struct TrieNode* createNode() {
    struct TrieNode* node = (struct TrieNode*)malloc(sizeof(struct TrieNode));
    node->data = NULL;
    node->isEndOfPath = 0;

    // Initialize children to NULL
    for (int i = 0; i < ALPHABET_SIZE; i++) {
        node->children[i] = NULL;
    }

    return node;
}

// JNI function to initialize the root node (called from Java to set up the Trie)
JNIEXPORT void JNICALL Java_TrieJNI_initialize(JNIEnv* env, jobject obj) {
    root = createNode();
}

// JNI function to insert a path into the Trie
JNIEXPORT void JNICALL Java_TrieJNI_insert(JNIEnv* env, jobject obj, jstring path, jstring data) {
    if (root == NULL) {
        // Root should be initialized before inserting
        printf("Error: Trie is not initialized\n");
        return;
    }

    const char* path_str = (*env)->GetStringUTFChars(env, path, 0);
    const char* data_str = (*env)->GetStringUTFChars(env, data, 0);

    // Insert the path into the Trie
    insert(root, path_str, data_str);

    (*env)->ReleaseStringUTFChars(env, path, path_str);
    (*env)->ReleaseStringUTFChars(env, data, data_str);
}

// JNI function to lookup a path in the Trie
JNIEXPORT jstring JNICALL Java_TrieJNI_lookup(JNIEnv* env, jobject obj, jstring path) {
    if (root == NULL) {
        // Root should be initialized before looking up
        printf("Error: Trie is not initialized\n");
        return NULL;
    }

    const char* path_str = (*env)->GetStringUTFChars(env, path, 0);

    // Look up the path in the Trie
    char* result = lookup(root, path_str);
    (*env)->ReleaseStringUTFChars(env, path, path_str);

    // Return the file path as a Java string
    if (result != NULL) {
        return (*env)->NewStringUTF(env, result);
    } else {
        return NULL;  // Return null if the path is not found
    }
}

// Insert a path into the Trie
void insert(struct TrieNode* root, const char* path, const char* data) {
    struct TrieNode* node = root;

    // Traverse the path character by character
    for (int i = 0; path[i] != '\0'; i++) {
        int index = path[i] - 'a';  // Convert char to index

        // If the child node doesn't exist, create it
        if (node->children[index] == NULL) {
            node->children[index] = createNode();
        }

        node = node->children[index];
    }

    // Store the file path at the end node
    node->data = strdup(data);
    node->isEndOfPath = 1;  // Mark as the end of a valid path
}

// Lookup a path in the Trie
char* lookup(struct TrieNode* root, const char* path) {
    struct TrieNode* node = root;

    // Traverse the Trie based on path characters
    for (int i = 0; path[i] != '\0'; i++) {
        int index = path[i] - 'a';  // Convert char to index

        // If no child exists for the character, return NULL (path not found)
        if (node->children[index] == NULL) {
            return NULL;
        }

        node = node->children[index];
    }

    // Return the file path if it's the end of a valid path
    return node->isEndOfPath ? node->data : NULL;
}

// Free memory for the Trie (optional cleanup)
void freeTrie(struct TrieNode* root) {
    if (root == NULL) return;

    for (int i = 0; i < ALPHABET_SIZE; i++) {
        freeTrie(root->children[i]);
    }

    if (root->data) {
        free(root->data);
    }

    free(root);
}

int main() {
    // Initialize the Trie
    root = createNode();

    // Insert paths into the Trie
    insert(root, "apiuseruserdetailsjson", "/path/to/api/user/userdetails.json");

    // Lookup a path
    char* result = lookup(root, "apiuseruserdetailsjson");
    if (result != NULL) {
        printf("Found path: %s\n", result);
    } else {
        printf("Path not found\n");
    }

    // Cleanup memory (for non-JNI testing)
    freeTrie(root);

    return 0;
}
